# Generated by Django 3.2 on 2021-05-22 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.EmailField(default='none@none', max_length=254),
        ),
        migrations.AlterField(
            model_name='contato',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dataCriacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
