# Generated by Django 3.2.4 on 2021-06-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_contato_idcontato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
